
member = [
    'QA_YT0007999981',
    'QA_YT0007999982',
    'QA_YT0007999983',
    'QA_YT0007999984',
    'QA_YT0007999985',
    'QA_YT0007999986',
    'QA_YT0007999987',
    'QA_YT0007999988',
    'QA_YT0007999989',
    'QA_YT0007999990',
    'QA_YT0007999991',
    'QA_YT0007999992',
    'QA_YT0007999993',
    'QA_YT0007999994',
    'QA_YT0007999995',
    'QA_YT0007999996',
    'QA_YT0007999997',
    'QA_YT0007999998',
    'QA_YT0007999999',
    'QA_YT0008000000',
]

memberadd  = [


]

usersimulation_list = [
    'self.user.SecurityList_sendEmail()',
    'self.user.WithdrawApplication()',
    'self.user.Deposit()',
    'self.user.BetRecoed()',
    'self.user.Transaction()',
    'self.user.updatingBalance()',
]

game_list = [
    'self.game.goPGelgame()',
    'self.game.goTOGelgame()',
    'self.game.goAEelgame()',
    'self.game.goSWelgame()',
    'self.game.goDTelgame()',
    'self.game.goGPK2elgame()',
    'self.game.goJSelgame()',
    'self.game.goPTelgame()',
    'self.game.goJDBelgame()',
    'self.game.goHBelgame()',
    'self.game.goSYelgame()',
    'self.game.goFGargame()',
    'self.game.goGPKelgame()',
    'self.game.goKAelgame()',
    'self.game.goPNGelgame()',
    'self.game.goMTelgame()',
    'self.game.goGHelgame()',
    'self.game.goICGelgame()',
    'self.game.goTHfish()',
    'self.game.goAPfish()',
    'self.game.goGPKfish()',
    'self.game.goFGfish()',
    'self.game.goJDBfish()',
    'self.game.goLEGfish()',
    'self.game.goVGfish()',
    'self.game.goMWfish()',
    'self.game.goFGbird()',
    'self.game.goMTfish()',
    'self.game.goICGfish()',
    'self.game.goBSPfish()',
]

entergame_list = [
    'self.entergame.enterGPKfish()',
    'self.entergame.enterRMboard()',
    'self.entergame.enterGPKboard()',
    'self.entergame.enterDTboard()',
    'self.entergame.enterAPboard()',
    'self.entergame.enterVGboard()',
    'self.entergame.enterFSboard()',
    'self.entergame.enterTOGboard()',
    'self.entergame.enterNWboard()',
    'self.entergame.enterMWboard()',
    'self.entergame.enterJSboard()',
    'self.entergame.enterLEGboard()',
    'self.entergame.enterJDBboard()',
    'self.entergame.enterGMGboard()',
    'self.entergame.enterMTboard()',
    'self.entergame.enterSYboard()',
    'self.entergame.enterTHboard()',
    'self.entergame.enterGPKfish()',
    'self.entergame.enterAPfish()',
    'self.entergame.enterJDBfish()',
    'self.entergame.enterFGfish()',
    'self.entergame.enterPSfish()',
    'self.entergame.enterTHfish()',
    'self.entergame.enterLEGfish()',
    'self.entergame.enterMTfish()',
    'self.entergame.enterVGfish()',
    'self.entergame.enterR8fish()',
    'self.entergame.enterBBINlive()',
    'self.entergame.enterAGlive()',
    'self.entergame.enterPTlive()',
    'self.entergame.enterMGlive()',
    'self.entergame.enterABlive()',
    'self.entergame.enterEVOlive()',
    'self.entergame.enterGDlive()',
    'self.entergame.enterGPKlive()',
    'self.entergame.enterSBlive()',
    'self.entergame.enterOGlive()',
    'self.entergame.enterSABAsport()',
    'self.entergame.enter3singsport()',
    'self.entergame.enterBBINsport()',
    'self.entergame.enterCMDsport()',
    'self.entergame.enterIMsport()',
    'self.entergame.enterCRsport()',
    'self.entergame.enterDTsport()',
    'self.entergame.enterGPKlottery()',
    'self.entergame.enterGPK2lottery()',
    'self.entergame.enterGPK3lottery()',
    'self.entergame.enterLLlottery()',
    'self.entergame.enterLBlottery()',
    'self.entergame.enterSYlottery()',
    'self.entergame.enterBBINlottery()',
    'self.entergame.enterIGlottery()',
]